#
# Copyright © 2016-2024 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tb-redis-insight
spec:
  serviceName: tb-redis-insight
  replicas: 1
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: tb-redis-insight
  template:
    metadata:
      labels:
        app: tb-redis-insight
    spec:
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        role: tb-additional
      containers:
        - name: server
          imagePullPolicy: Always
          image: redislabs/redisinsight:2.58.0
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 5540
              name: http5540
      restartPolicy: Always
