#
# Copyright © 2016-2023 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-tests-publishers-config
  labels:
    name: broker-tests-publishers-config
data:
  tb-mqtt-broker-performance-tests.conf: |
    # Memory for 7Gi pod
    export JAVA_OPTS="$JAVA_OPTS -Xmx3g -Xms3g -Xss320k -XX:+AlwaysPreTouch"
    export JAVA_OPTS="$JAVA_OPTS -Dplatform=deb"
    export JAVA_OPTS="$JAVA_OPTS -XX:+IgnoreUnrecognizedVMOptions -XX:+HeapDumpOnOutOfMemoryError"
    export JAVA_OPTS="$JAVA_OPTS -XX:-UseBiasedLocking -XX:+UseTLAB -XX:+ResizeTLAB -XX:+PerfDisableSharedMem -XX:+UseCondCardMark"
    export JAVA_OPTS="$JAVA_OPTS -XX:CMSWaitDuration=10000 -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+CMSParallelInitialMarkEnabled"
    export JAVA_OPTS="$JAVA_OPTS -XX:+CMSEdenChunksRecordAlways -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly"
    
    # JMX
    export JAVA_OPTS="$JAVA_OPTS -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9199 -Dcom.sun.management.jmxremote.rmi.port=9199"
    export JAVA_OPTS="$JAVA_OPTS -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1"
    
    export LOADER_PATH==/usr/share/tb-mqtt-broker-performance-tests/conf
  logback.xml: |
    <?xml version="1.0" encoding="UTF-8" ?>
    <configuration scan="true">
        
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <layout class="ch.qos.logback.classic.PatternLayout">
                <Pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</Pattern>
            </layout>
        </appender>
        
        <logger name="org.thingsboard.mqtt.broker" level="INFO"/>
        
        <logger name="org.thingsboard.mqtt.broker.service.PublisherServiceImpl" level="INFO"/>
        <logger name="org.thingsboard.mqtt.broker.service.SubscriberServiceImpl" level="INFO"/>
        <logger name="org.thingsboard.mqtt.broker.service.ClusterProcessServiceImpl" level="INFO"/>
        
        <root level="INFO">
            <appender-ref ref="STDOUT"/>
        </root>
    
    </configuration>
  test_run_config.json: |
    {
      "publisherGroups": [
        {
          "id": 1,
          "publishers": 150000,
          "topicPrefix": "usa/lIEIM/1/",
          "clientIdPrefix": null
        },
        {
          "id": 2,
          "publishers": 150000,
          "topicPrefix": "usa/cpvvh/2/",
          "clientIdPrefix": null
        },
        {
          "id": 3,
          "publishers": 150000,
          "topicPrefix": "usa/FHJTE/3/",
          "clientIdPrefix": null
        },
        {
          "id": 4,
          "publishers": 150000,
          "topicPrefix": "usa/THEkK/4/",
          "clientIdPrefix": null
        },
        {
          "id": 5,
          "publishers": 150000,
          "topicPrefix": "usa/WNZFF/5/",
          "clientIdPrefix": null
        },
        {
          "id": 6,
          "publishers": 150000,
          "topicPrefix": "usa/dDXgL/6/",
          "clientIdPrefix": null
        },
        {
          "id": 7,
          "publishers": 150000,
          "topicPrefix": "usa/ODrBl/7/",
          "clientIdPrefix": null
        },
        {
          "id": 8,
          "publishers": 150000,
          "topicPrefix": "usa/Wlfdh/8/",
          "clientIdPrefix": null
        },
        {
          "id": 9,
          "publishers": 150000,
          "topicPrefix": "usa/LKTCS/9/",
          "clientIdPrefix": null
        },
        {
          "id": 10,
          "publishers": 150000,
          "topicPrefix": "usa/TviKe/10/",
          "clientIdPrefix": null
        },
        {
          "id": 11,
          "publishers": 150000,
          "topicPrefix": "usa/eHTsu/11/",
          "clientIdPrefix": null
        },
        {
          "id": 12,
          "publishers": 150000,
          "topicPrefix": "usa/xGuXv/12/",
          "clientIdPrefix": null
        },
        {
          "id": 13,
          "publishers": 150000,
          "topicPrefix": "usa/ttDrX/13/",
          "clientIdPrefix": null
        },
        {
          "id": 14,
          "publishers": 150000,
          "topicPrefix": "usa/YdXtp/14/",
          "clientIdPrefix": null
        },
        {
          "id": 15,
          "publishers": 150000,
          "topicPrefix": "usa/dWjnS/15/",
          "clientIdPrefix": null
        },
        {
          "id": 16,
          "publishers": 150000,
          "topicPrefix": "usa/ShoBt/16/",
          "clientIdPrefix": null
        },
        {
          "id": 17,
          "publishers": 150000,
          "topicPrefix": "usa/SMDgQ/17/",
          "clientIdPrefix": null
        },
        {
          "id": 18,
          "publishers": 150000,
          "topicPrefix": "usa/CNekL/18/",
          "clientIdPrefix": null
        },
        {
          "id": 19,
          "publishers": 150000,
          "topicPrefix": "usa/KEnfF/19/",
          "clientIdPrefix": null
        },
        {
          "id": 20,
          "publishers": 150000,
          "topicPrefix": "usa/mpxPz/20/",
          "clientIdPrefix": null
        },
        {
          "id": 21,
          "publishers": 150000,
          "topicPrefix": "usa/ngHuP/21/",
          "clientIdPrefix": null
        },
        {
          "id": 22,
          "publishers": 150000,
          "topicPrefix": "usa/iQusk/22/",
          "clientIdPrefix": null
        },
        {
          "id": 23,
          "publishers": 150000,
          "topicPrefix": "usa/tFWtK/23/",
          "clientIdPrefix": null
        },
        {
          "id": 24,
          "publishers": 150000,
          "topicPrefix": "usa/SGHwK/24/",
          "clientIdPrefix": null
        },
        {
          "id": 25,
          "publishers": 150000,
          "topicPrefix": "usa/bWfSp/25/",
          "clientIdPrefix": null
        },
        {
          "id": 26,
          "publishers": 150000,
          "topicPrefix": "usa/dQGCN/26/",
          "clientIdPrefix": null
        },
        {
          "id": 27,
          "publishers": 150000,
          "topicPrefix": "usa/xZIuo/27/",
          "clientIdPrefix": null
        },
        {
          "id": 28,
          "publishers": 150000,
          "topicPrefix": "usa/RxkcS/28/",
          "clientIdPrefix": null
        },
        {
          "id": 29,
          "publishers": 150000,
          "topicPrefix": "usa/YbbPp/29/",
          "clientIdPrefix": null
        },
        {
          "id": 30,
          "publishers": 150000,
          "topicPrefix": "usa/rFLrG/30/",
          "clientIdPrefix": null
        },
        {
          "id": 31,
          "publishers": 150000,
          "topicPrefix": "usa/EuEKu/31/",
          "clientIdPrefix": null
        },
        {
          "id": 32,
          "publishers": 150000,
          "topicPrefix": "usa/biILf/32/",
          "clientIdPrefix": null
        },
        {
          "id": 33,
          "publishers": 150000,
          "topicPrefix": "usa/EZhHg/33/",
          "clientIdPrefix": null
        },
        {
          "id": 34,
          "publishers": 150000,
          "topicPrefix": "usa/fMVxv/34/",
          "clientIdPrefix": null
        },
        {
          "id": 35,
          "publishers": 150000,
          "topicPrefix": "usa/Oospo/35/",
          "clientIdPrefix": null
        },
        {
          "id": 36,
          "publishers": 150000,
          "topicPrefix": "usa/lceAJ/36/",
          "clientIdPrefix": null
        },
        {
          "id": 37,
          "publishers": 150000,
          "topicPrefix": "usa/GlogP/37/",
          "clientIdPrefix": null
        },
        {
          "id": 38,
          "publishers": 150000,
          "topicPrefix": "usa/JlXVs/38/",
          "clientIdPrefix": null
        },
        {
          "id": 39,
          "publishers": 150000,
          "topicPrefix": "usa/ArKrA/39/",
          "clientIdPrefix": null
        },
        {
          "id": 40,
          "publishers": 150000,
          "topicPrefix": "usa/zzMPo/40/",
          "clientIdPrefix": null
        },
        {
          "id": 41,
          "publishers": 150000,
          "topicPrefix": "usa/cdxXU/41/",
          "clientIdPrefix": null
        },
        {
          "id": 42,
          "publishers": 150000,
          "topicPrefix": "usa/OTDib/42/",
          "clientIdPrefix": null
        },
        {
          "id": 43,
          "publishers": 150000,
          "topicPrefix": "usa/WyaRN/43/",
          "clientIdPrefix": null
        },
        {
          "id": 44,
          "publishers": 150000,
          "topicPrefix": "usa/iqWQj/44/",
          "clientIdPrefix": null
        },
        {
          "id": 45,
          "publishers": 150000,
          "topicPrefix": "usa/TXRAX/45/",
          "clientIdPrefix": null
        },
        {
          "id": 46,
          "publishers": 150000,
          "topicPrefix": "usa/Uuday/46/",
          "clientIdPrefix": null
        },
        {
          "id": 47,
          "publishers": 150000,
          "topicPrefix": "usa/pCxVi/47/",
          "clientIdPrefix": null
        },
        {
          "id": 48,
          "publishers": 150000,
          "topicPrefix": "usa/JlgTE/48/",
          "clientIdPrefix": null
        },
        {
          "id": 49,
          "publishers": 150000,
          "topicPrefix": "usa/pbvQU/49/",
          "clientIdPrefix": null
        },
        {
          "id": 50,
          "publishers": 150000,
          "topicPrefix": "usa/lIMoO/50/",
          "clientIdPrefix": null
        },
        {
          "id": 51,
          "publishers": 150000,
          "topicPrefix": "usa/SXnnc/51/",
          "clientIdPrefix": null
        },
        {
          "id": 52,
          "publishers": 150000,
          "topicPrefix": "usa/EjYaB/52/",
          "clientIdPrefix": null
        },
        {
          "id": 53,
          "publishers": 150000,
          "topicPrefix": "usa/RpXrT/53/",
          "clientIdPrefix": null
        },
        {
          "id": 54,
          "publishers": 150000,
          "topicPrefix": "usa/SDbhX/54/",
          "clientIdPrefix": null
        },
        {
          "id": 55,
          "publishers": 150000,
          "topicPrefix": "usa/ohiHm/55/",
          "clientIdPrefix": null
        },
        {
          "id": 56,
          "publishers": 150000,
          "topicPrefix": "usa/gdJGK/56/",
          "clientIdPrefix": null
        },
        {
          "id": 57,
          "publishers": 150000,
          "topicPrefix": "usa/GQjxf/57/",
          "clientIdPrefix": null
        },
        {
          "id": 58,
          "publishers": 150000,
          "topicPrefix": "usa/wdEfk/58/",
          "clientIdPrefix": null
        },
        {
          "id": 59,
          "publishers": 150000,
          "topicPrefix": "usa/VBhRy/59/",
          "clientIdPrefix": null
        },
        {
          "id": 60,
          "publishers": 150000,
          "topicPrefix": "usa/iGwQj/60/",
          "clientIdPrefix": null
        },
        {
          "id": 61,
          "publishers": 150000,
          "topicPrefix": "usa/MYIrp/61/",
          "clientIdPrefix": null
        },
        {
          "id": 62,
          "publishers": 150000,
          "topicPrefix": "usa/kbbfz/62/",
          "clientIdPrefix": null
        },
        {
          "id": 63,
          "publishers": 150000,
          "topicPrefix": "usa/kPSpm/63/",
          "clientIdPrefix": null
        },
        {
          "id": 64,
          "publishers": 150000,
          "topicPrefix": "usa/vRKvy/64/",
          "clientIdPrefix": null
        },
        {
          "id": 65,
          "publishers": 150000,
          "topicPrefix": "usa/hUpqY/65/",
          "clientIdPrefix": null
        },
        {
          "id": 66,
          "publishers": 150000,
          "topicPrefix": "usa/rtFiU/66/",
          "clientIdPrefix": null
        },
        {
          "id": 67,
          "publishers": 150000,
          "topicPrefix": "usa/yFyMs/67/",
          "clientIdPrefix": null
        },
        {
          "id": 68,
          "publishers": 150000,
          "topicPrefix": "usa/AVVpA/68/",
          "clientIdPrefix": null
        },
        {
          "id": 69,
          "publishers": 150000,
          "topicPrefix": "usa/tIUlt/69/",
          "clientIdPrefix": null
        },
        {
          "id": 70,
          "publishers": 150000,
          "topicPrefix": "usa/ztMLo/70/",
          "clientIdPrefix": null
        },
        {
          "id": 71,
          "publishers": 150000,
          "topicPrefix": "usa/cGkhm/71/",
          "clientIdPrefix": null
        },
        {
          "id": 72,
          "publishers": 150000,
          "topicPrefix": "usa/AZxpX/72/",
          "clientIdPrefix": null
        },
        {
          "id": 73,
          "publishers": 150000,
          "topicPrefix": "usa/ftjPg/73/",
          "clientIdPrefix": null
        },
        {
          "id": 74,
          "publishers": 150000,
          "topicPrefix": "usa/wffUs/74/",
          "clientIdPrefix": null
        },
        {
          "id": 75,
          "publishers": 150000,
          "topicPrefix": "usa/BnvNo/75/",
          "clientIdPrefix": null
        },
        {
          "id": 76,
          "publishers": 150000,
          "topicPrefix": "usa/zjrGz/76/",
          "clientIdPrefix": null
        },
        {
          "id": 77,
          "publishers": 150000,
          "topicPrefix": "usa/LYhgv/77/",
          "clientIdPrefix": null
        },
        {
          "id": 78,
          "publishers": 150000,
          "topicPrefix": "usa/DOrrW/78/",
          "clientIdPrefix": null
        },
        {
          "id": 79,
          "publishers": 150000,
          "topicPrefix": "usa/CCelY/79/",
          "clientIdPrefix": null
        },
        {
          "id": 80,
          "publishers": 150000,
          "topicPrefix": "usa/RYcEM/80/",
          "clientIdPrefix": null
        }
      ],
      "subscriberGroups": [],
      "dummyClients": 0,
      "secondsToRun": 180,
      "additionalSecondsToWait": 30,
      "maxMsgsPerPublisherPerSecond": 1,
      "publisherQosValue": 1,
      "subscriberQosValue": 1,
      "minPayloadSize": 1,
      "maxConcurrentOperations": 3000,
      "telemetryKeys": [
        "lat",
        "long",
        "speed",
        "fuel",
        "batLvl"
      ]
    }
